// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MsgType int32

const (
	MsgType_req MsgType = 0
	MsgType_res MsgType = 1
	MsgType_hea MsgType = 2
)

var MsgType_name = map[int32]string{
	0: "req",
	1: "res",
	2: "hea",
}

var MsgType_value = map[string]int32{
	"req": 0,
	"res": 1,
	"hea": 2,
}

func (x MsgType) String() string {
	return proto.EnumName(MsgType_name, int32(x))
}

func (MsgType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{0}
}

type Msg struct {
	Version              int32    `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	MsgType              MsgType  `protobuf:"varint,3,opt,name=msgType,proto3,enum=pb.MsgType" json:"msgType,omitempty"`
	Batch                bool     `protobuf:"varint,4,opt,name=batch,proto3" json:"batch,omitempty"`
	CodecType            int32    `protobuf:"varint,5,opt,name=codecType,proto3" json:"codecType,omitempty"`
	Data                 []byte   `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Msg) Reset()         { *m = Msg{} }
func (m *Msg) String() string { return proto.CompactTextString(m) }
func (*Msg) ProtoMessage()    {}
func (*Msg) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{0}
}

func (m *Msg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Msg.Unmarshal(m, b)
}
func (m *Msg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Msg.Marshal(b, m, deterministic)
}
func (m *Msg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Msg.Merge(m, src)
}
func (m *Msg) XXX_Size() int {
	return xxx_messageInfo_Msg.Size(m)
}
func (m *Msg) XXX_DiscardUnknown() {
	xxx_messageInfo_Msg.DiscardUnknown(m)
}

var xxx_messageInfo_Msg proto.InternalMessageInfo

func (m *Msg) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Msg) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Msg) GetMsgType() MsgType {
	if m != nil {
		return m.MsgType
	}
	return MsgType_req
}

func (m *Msg) GetBatch() bool {
	if m != nil {
		return m.Batch
	}
	return false
}

func (m *Msg) GetCodecType() int32 {
	if m != nil {
		return m.CodecType
	}
	return 0
}

func (m *Msg) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Batch struct {
	Data                 [][]byte `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Batch) Reset()         { *m = Batch{} }
func (m *Batch) String() string { return proto.CompactTextString(m) }
func (*Batch) ProtoMessage()    {}
func (*Batch) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{1}
}

func (m *Batch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Batch.Unmarshal(m, b)
}
func (m *Batch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Batch.Marshal(b, m, deterministic)
}
func (m *Batch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Batch.Merge(m, src)
}
func (m *Batch) XXX_Size() int {
	return xxx_messageInfo_Batch.Size(m)
}
func (m *Batch) XXX_DiscardUnknown() {
	xxx_messageInfo_Batch.DiscardUnknown(m)
}

var xxx_messageInfo_Batch proto.InternalMessageInfo

func (m *Batch) GetData() [][]byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Request struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Method               string   `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	NoResponse           bool     `protobuf:"varint,4,opt,name=noResponse,proto3" json:"noResponse,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{2}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Request) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Request) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Request) GetNoResponse() bool {
	if m != nil {
		return m.NoResponse
	}
	return false
}

type Response struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	ErrMsg               string   `protobuf:"bytes,3,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Response) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Response) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func init() {
	proto.RegisterEnum("pb.MsgType", MsgType_name, MsgType_value)
	proto.RegisterType((*Msg)(nil), "pb.Msg")
	proto.RegisterType((*Batch)(nil), "pb.Batch")
	proto.RegisterType((*Request)(nil), "pb.Request")
	proto.RegisterType((*Response)(nil), "pb.Response")
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor_77a6da22d6a3feb1) }

var fileDescriptor_77a6da22d6a3feb1 = []byte{
	// 272 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x51, 0xcb, 0x4a, 0xc4, 0x30,
	0x14, 0x35, 0x49, 0x1f, 0xd3, 0xab, 0x0c, 0x25, 0xc8, 0x10, 0x50, 0x24, 0x14, 0x85, 0xe2, 0xa2,
	0x0b, 0xfd, 0x03, 0x17, 0xee, 0xba, 0x09, 0xfe, 0x40, 0x1f, 0x97, 0xb6, 0x8b, 0x69, 0x32, 0x49,
	0x15, 0xfc, 0x19, 0xbf, 0x55, 0x26, 0x6d, 0x67, 0x06, 0x66, 0x77, 0x1e, 0xdc, 0x73, 0x0e, 0x09,
	0x24, 0xd6, 0x34, 0x85, 0xb1, 0x7a, 0xd2, 0x9c, 0x9a, 0x3a, 0xfb, 0x23, 0xc0, 0x4a, 0xd7, 0x71,
	0x01, 0xf1, 0x0f, 0x5a, 0x37, 0xe8, 0x51, 0x10, 0x49, 0xf2, 0x50, 0xad, 0x94, 0x6f, 0x81, 0x0e,
	0xad, 0xa0, 0x92, 0xe4, 0x4c, 0xd1, 0xa1, 0xe5, 0x2f, 0x10, 0xef, 0x5d, 0xf7, 0xf5, 0x6b, 0x50,
	0x30, 0x49, 0xf2, 0xed, 0xdb, 0x6d, 0x61, 0xea, 0xa2, 0x9c, 0x25, 0xb5, 0x7a, 0xfc, 0x1e, 0xc2,
	0xba, 0x9a, 0x9a, 0x5e, 0x04, 0x92, 0xe4, 0x1b, 0x35, 0x13, 0xfe, 0x08, 0x49, 0xa3, 0x5b, 0x6c,
	0xfc, 0x79, 0xe8, 0x8b, 0xce, 0x02, 0xe7, 0x10, 0xb4, 0xd5, 0x54, 0x89, 0x48, 0x92, 0xfc, 0x4e,
	0x79, 0x9c, 0x3d, 0x40, 0xf8, 0xe1, 0x4f, 0x57, 0x93, 0x48, 0x76, 0x32, 0x11, 0x62, 0x85, 0x87,
	0x6f, 0x74, 0xd3, 0x32, 0xf3, 0xb8, 0x3d, 0xf0, 0x33, 0x77, 0x10, 0xed, 0x71, 0xea, 0xf5, 0x3c,
	0x3d, 0x51, 0x0b, 0x3b, 0xc5, 0xb0, 0x73, 0x07, 0x7f, 0x02, 0x18, 0xb5, 0x42, 0x67, 0xf4, 0xe8,
	0x70, 0x19, 0x7c, 0xa1, 0x64, 0x9f, 0xb0, 0x59, 0xf1, 0x55, 0xcf, 0x9a, 0x47, 0x2f, 0xf2, 0x76,
	0x10, 0xa1, 0xb5, 0xa5, 0xeb, 0x7c, 0x4b, 0xa2, 0x16, 0xf6, 0xfa, 0x0c, 0xf1, 0xf2, 0x4e, 0x3c,
	0x06, 0x66, 0xf1, 0x90, 0xde, 0xcc, 0xc0, 0xa5, 0xe4, 0x08, 0x7a, 0xac, 0x52, 0x5a, 0x47, 0xfe,
	0x77, 0xde, 0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0x61, 0x9c, 0xb3, 0x20, 0xaa, 0x01, 0x00, 0x00,
}
