// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MsgType int32

const (
	MsgType_req MsgType = 0
	MsgType_res MsgType = 1
	MsgType_hea MsgType = 2
)

var MsgType_name = map[int32]string{
	0: "req",
	1: "res",
	2: "hea",
}

var MsgType_value = map[string]int32{
	"req": 0,
	"res": 1,
	"hea": 2,
}

func (x MsgType) String() string {
	return proto.EnumName(MsgType_name, int32(x))
}

func (MsgType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{0}
}

type CodecType int32

const (
	CodecType_invalid  CodecType = 0
	CodecType_json     CodecType = 1
	CodecType_protobuf CodecType = 2
	CodecType_xml      CodecType = 3
	CodecType_gob      CodecType = 4
	CodecType_bytes    CodecType = 5
)

var CodecType_name = map[int32]string{
	0: "invalid",
	1: "json",
	2: "protobuf",
	3: "xml",
	4: "gob",
	5: "bytes",
}

var CodecType_value = map[string]int32{
	"invalid":  0,
	"json":     1,
	"protobuf": 2,
	"xml":      3,
	"gob":      4,
	"bytes":    5,
}

func (x CodecType) String() string {
	return proto.EnumName(CodecType_name, int32(x))
}

func (CodecType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{1}
}

type Msg struct {
	Version              float32   `protobuf:"fixed32,1,opt,name=version,proto3" json:"version,omitempty"`
	Id                   int64     `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	MsgType              MsgType   `protobuf:"varint,3,opt,name=msgType,proto3,enum=pb.MsgType" json:"msgType,omitempty"`
	Batch                bool      `protobuf:"varint,4,opt,name=batch,proto3" json:"batch,omitempty"`
	CodecType            CodecType `protobuf:"varint,5,opt,name=codecType,proto3,enum=pb.CodecType" json:"codecType,omitempty"`
	Data                 []byte    `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Msg) Reset()         { *m = Msg{} }
func (m *Msg) String() string { return proto.CompactTextString(m) }
func (*Msg) ProtoMessage()    {}
func (*Msg) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{0}
}

func (m *Msg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Msg.Unmarshal(m, b)
}
func (m *Msg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Msg.Marshal(b, m, deterministic)
}
func (m *Msg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Msg.Merge(m, src)
}
func (m *Msg) XXX_Size() int {
	return xxx_messageInfo_Msg.Size(m)
}
func (m *Msg) XXX_DiscardUnknown() {
	xxx_messageInfo_Msg.DiscardUnknown(m)
}

var xxx_messageInfo_Msg proto.InternalMessageInfo

func (m *Msg) GetVersion() float32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Msg) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Msg) GetMsgType() MsgType {
	if m != nil {
		return m.MsgType
	}
	return MsgType_req
}

func (m *Msg) GetBatch() bool {
	if m != nil {
		return m.Batch
	}
	return false
}

func (m *Msg) GetCodecType() CodecType {
	if m != nil {
		return m.CodecType
	}
	return CodecType_invalid
}

func (m *Msg) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Batch struct {
	Data                 [][]byte `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Batch) Reset()         { *m = Batch{} }
func (m *Batch) String() string { return proto.CompactTextString(m) }
func (*Batch) ProtoMessage()    {}
func (*Batch) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{1}
}

func (m *Batch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Batch.Unmarshal(m, b)
}
func (m *Batch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Batch.Marshal(b, m, deterministic)
}
func (m *Batch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Batch.Merge(m, src)
}
func (m *Batch) XXX_Size() int {
	return xxx_messageInfo_Batch.Size(m)
}
func (m *Batch) XXX_DiscardUnknown() {
	xxx_messageInfo_Batch.DiscardUnknown(m)
}

var xxx_messageInfo_Batch proto.InternalMessageInfo

func (m *Batch) GetData() [][]byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Request struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Method               string   `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	NoResponse           bool     `protobuf:"varint,4,opt,name=noResponse,proto3" json:"noResponse,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{2}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Request) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Request) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Request) GetNoResponse() bool {
	if m != nil {
		return m.NoResponse
	}
	return false
}

type Response struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	ErrMsg               string   `protobuf:"bytes,3,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Response) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Response) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func init() {
	proto.RegisterEnum("pb.MsgType", MsgType_name, MsgType_value)
	proto.RegisterEnum("pb.CodecType", CodecType_name, CodecType_value)
	proto.RegisterType((*Msg)(nil), "pb.Msg")
	proto.RegisterType((*Batch)(nil), "pb.Batch")
	proto.RegisterType((*Request)(nil), "pb.Request")
	proto.RegisterType((*Response)(nil), "pb.Response")
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor_77a6da22d6a3feb1) }

var fileDescriptor_77a6da22d6a3feb1 = []byte{
	// 331 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x51, 0xdb, 0x6a, 0xe3, 0x30,
	0x14, 0x8c, 0x24, 0x5f, 0x4f, 0xb2, 0x41, 0x1c, 0x96, 0x60, 0x58, 0x58, 0x4c, 0xd8, 0x05, 0x93,
	0x42, 0x1e, 0xda, 0x3f, 0x68, 0xa1, 0x6f, 0x7e, 0x11, 0xfd, 0x01, 0xcb, 0x56, 0x1d, 0x97, 0xc4,
	0x72, 0x2c, 0x27, 0x34, 0x1f, 0xd5, 0x7f, 0x2c, 0x96, 0xed, 0x24, 0xd0, 0xb7, 0x99, 0x33, 0x9a,
	0x39, 0x17, 0x41, 0xd8, 0x36, 0xf9, 0xb6, 0x69, 0x75, 0xa7, 0x91, 0x36, 0x72, 0xfd, 0x45, 0x80,
	0xa5, 0xa6, 0xc4, 0x08, 0xfc, 0xb3, 0x6a, 0x4d, 0xa5, 0xeb, 0x88, 0xc4, 0x24, 0xa1, 0x62, 0xa2,
	0xb8, 0x04, 0x5a, 0x15, 0x11, 0x8d, 0x49, 0xc2, 0x04, 0xad, 0x0a, 0xfc, 0x0f, 0xfe, 0xc1, 0x94,
	0x6f, 0x97, 0x46, 0x45, 0x2c, 0x26, 0xc9, 0xf2, 0x71, 0xbe, 0x6d, 0xe4, 0x36, 0x1d, 0x4a, 0x62,
	0xd2, 0xf0, 0x37, 0xb8, 0x32, 0xeb, 0xf2, 0x5d, 0xe4, 0xc4, 0x24, 0x09, 0xc4, 0x40, 0xf0, 0x01,
	0xc2, 0x5c, 0x17, 0x2a, 0xb7, 0x76, 0xd7, 0xda, 0x7f, 0xf5, 0xf6, 0x97, 0xa9, 0x28, 0x6e, 0x3a,
	0x22, 0x38, 0x45, 0xd6, 0x65, 0x91, 0x17, 0x93, 0x64, 0x21, 0x2c, 0x5e, 0xff, 0x01, 0xf7, 0xd9,
	0x26, 0x4d, 0x22, 0x89, 0xd9, 0x55, 0x54, 0xe0, 0x0b, 0x75, 0x3c, 0x29, 0xd3, 0x8d, 0x53, 0xf7,
	0xab, 0x38, 0x76, 0xea, 0x15, 0x78, 0x07, 0xd5, 0xed, 0xf4, 0xb0, 0x49, 0x28, 0x46, 0x76, 0x8d,
	0x61, 0xb7, 0x1e, 0xf8, 0x17, 0xa0, 0xd6, 0x42, 0x99, 0x46, 0xd7, 0x46, 0x8d, 0xf3, 0xdf, 0x55,
	0xd6, 0xaf, 0x10, 0x4c, 0xf8, 0x47, 0x9f, 0x29, 0x8f, 0xde, 0xe5, 0xad, 0xc0, 0x53, 0x6d, 0x9b,
	0x9a, 0xd2, 0x76, 0x09, 0xc5, 0xc8, 0x36, 0xff, 0xc0, 0x1f, 0xcf, 0x86, 0x3e, 0xb0, 0x56, 0x1d,
	0xf9, 0x6c, 0x00, 0x86, 0x93, 0x1e, 0xec, 0x54, 0xc6, 0xe9, 0x26, 0x85, 0xf0, 0x7a, 0x1d, 0x9c,
	0x83, 0x5f, 0xd5, 0xe7, 0x6c, 0x5f, 0x15, 0x7c, 0x86, 0x01, 0x38, 0x1f, 0x46, 0xd7, 0x9c, 0xe0,
	0x02, 0x02, 0xfb, 0xa5, 0xf2, 0xf4, 0xce, 0x69, 0x6f, 0xfd, 0x3c, 0xec, 0x39, 0xeb, 0x41, 0xa9,
	0x25, 0x77, 0x30, 0x04, 0x57, 0x5e, 0x3a, 0x65, 0xb8, 0x2b, 0x3d, 0xfb, 0xf0, 0xe9, 0x3b, 0x00,
	0x00, 0xff, 0xff, 0x50, 0x3f, 0x90, 0x7c, 0x08, 0x02, 0x00, 0x00,
}
