// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MsgType int32

const (
	MsgType_req MsgType = 0
	MsgType_res MsgType = 1
	MsgType_hea MsgType = 2
)

var MsgType_name = map[int32]string{
	0: "req",
	1: "res",
	2: "hea",
}

var MsgType_value = map[string]int32{
	"req": 0,
	"res": 1,
	"hea": 2,
}

func (x MsgType) String() string {
	return proto.EnumName(MsgType_name, int32(x))
}

func (MsgType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{0}
}

type CodecType int32

const (
	CodecType_invalid  CodecType = 0
	CodecType_json     CodecType = 1
	CodecType_protobuf CodecType = 2
	CodecType_xml      CodecType = 3
	CodecType_gob      CodecType = 4
	CodecType_bytes    CodecType = 5
)

var CodecType_name = map[int32]string{
	0: "invalid",
	1: "json",
	2: "protobuf",
	3: "xml",
	4: "gob",
	5: "bytes",
}

var CodecType_value = map[string]int32{
	"invalid":  0,
	"json":     1,
	"protobuf": 2,
	"xml":      3,
	"gob":      4,
	"bytes":    5,
}

func (x CodecType) String() string {
	return proto.EnumName(CodecType_name, int32(x))
}

func (CodecType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{1}
}

type CompressType int32

const (
	CompressType_nocom CompressType = 0
	CompressType_flate CompressType = 1
	CompressType_zlib  CompressType = 2
	CompressType_gzip  CompressType = 3
)

var CompressType_name = map[int32]string{
	0: "nocom",
	1: "flate",
	2: "zlib",
	3: "gzip",
}

var CompressType_value = map[string]int32{
	"nocom": 0,
	"flate": 1,
	"zlib":  2,
	"gzip":  3,
}

func (x CompressType) String() string {
	return proto.EnumName(CompressType_name, int32(x))
}

func (CompressType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{2}
}

type CompressLevel int32

const (
	CompressLevel_noCompression      CompressLevel = 0
	CompressLevel_bestSpeed          CompressLevel = 1
	CompressLevel_bestCompression    CompressLevel = 2
	CompressLevel_defaultCompression CompressLevel = 3
)

var CompressLevel_name = map[int32]string{
	0: "noCompression",
	1: "bestSpeed",
	2: "bestCompression",
	3: "defaultCompression",
}

var CompressLevel_value = map[string]int32{
	"noCompression":      0,
	"bestSpeed":          1,
	"bestCompression":    2,
	"defaultCompression": 3,
}

func (x CompressLevel) String() string {
	return proto.EnumName(CompressLevel_name, int32(x))
}

func (CompressLevel) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{3}
}

type Msg struct {
	Version              float32       `protobuf:"fixed32,1,opt,name=version,proto3" json:"version,omitempty"`
	Id                   int64         `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	MsgType              MsgType       `protobuf:"varint,3,opt,name=msgType,proto3,enum=pb.MsgType" json:"msgType,omitempty"`
	Batch                bool          `protobuf:"varint,4,opt,name=batch,proto3" json:"batch,omitempty"`
	CodecType            CodecType     `protobuf:"varint,5,opt,name=codecType,proto3,enum=pb.CodecType" json:"codecType,omitempty"`
	CompressType         CompressType  `protobuf:"varint,6,opt,name=compressType,proto3,enum=pb.CompressType" json:"compressType,omitempty"`
	CompressLevel        CompressLevel `protobuf:"varint,7,opt,name=compressLevel,proto3,enum=pb.CompressLevel" json:"compressLevel,omitempty"`
	Data                 []byte        `protobuf:"bytes,8,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Msg) Reset()         { *m = Msg{} }
func (m *Msg) String() string { return proto.CompactTextString(m) }
func (*Msg) ProtoMessage()    {}
func (*Msg) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{0}
}

func (m *Msg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Msg.Unmarshal(m, b)
}
func (m *Msg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Msg.Marshal(b, m, deterministic)
}
func (m *Msg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Msg.Merge(m, src)
}
func (m *Msg) XXX_Size() int {
	return xxx_messageInfo_Msg.Size(m)
}
func (m *Msg) XXX_DiscardUnknown() {
	xxx_messageInfo_Msg.DiscardUnknown(m)
}

var xxx_messageInfo_Msg proto.InternalMessageInfo

func (m *Msg) GetVersion() float32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Msg) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Msg) GetMsgType() MsgType {
	if m != nil {
		return m.MsgType
	}
	return MsgType_req
}

func (m *Msg) GetBatch() bool {
	if m != nil {
		return m.Batch
	}
	return false
}

func (m *Msg) GetCodecType() CodecType {
	if m != nil {
		return m.CodecType
	}
	return CodecType_invalid
}

func (m *Msg) GetCompressType() CompressType {
	if m != nil {
		return m.CompressType
	}
	return CompressType_nocom
}

func (m *Msg) GetCompressLevel() CompressLevel {
	if m != nil {
		return m.CompressLevel
	}
	return CompressLevel_noCompression
}

func (m *Msg) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Batch struct {
	Async                bool     `protobuf:"varint,1,opt,name=async,proto3" json:"async,omitempty"`
	Data                 [][]byte `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Batch) Reset()         { *m = Batch{} }
func (m *Batch) String() string { return proto.CompactTextString(m) }
func (*Batch) ProtoMessage()    {}
func (*Batch) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{1}
}

func (m *Batch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Batch.Unmarshal(m, b)
}
func (m *Batch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Batch.Marshal(b, m, deterministic)
}
func (m *Batch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Batch.Merge(m, src)
}
func (m *Batch) XXX_Size() int {
	return xxx_messageInfo_Batch.Size(m)
}
func (m *Batch) XXX_DiscardUnknown() {
	xxx_messageInfo_Batch.DiscardUnknown(m)
}

var xxx_messageInfo_Batch proto.InternalMessageInfo

func (m *Batch) GetAsync() bool {
	if m != nil {
		return m.Async
	}
	return false
}

func (m *Batch) GetData() [][]byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Request struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Method               string   `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	NoRequest            bool     `protobuf:"varint,3,opt,name=noRequest,proto3" json:"noRequest,omitempty"`
	NoResponse           bool     `protobuf:"varint,4,opt,name=noResponse,proto3" json:"noResponse,omitempty"`
	Data                 []byte   `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{2}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Request) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Request) GetNoRequest() bool {
	if m != nil {
		return m.NoRequest
	}
	return false
}

func (m *Request) GetNoResponse() bool {
	if m != nil {
		return m.NoResponse
	}
	return false
}

func (m *Request) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Response struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	ErrMsg               string   `protobuf:"bytes,3,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Response) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Response) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func init() {
	proto.RegisterEnum("pb.MsgType", MsgType_name, MsgType_value)
	proto.RegisterEnum("pb.CodecType", CodecType_name, CodecType_value)
	proto.RegisterEnum("pb.CompressType", CompressType_name, CompressType_value)
	proto.RegisterEnum("pb.CompressLevel", CompressLevel_name, CompressLevel_value)
	proto.RegisterType((*Msg)(nil), "pb.Msg")
	proto.RegisterType((*Batch)(nil), "pb.Batch")
	proto.RegisterType((*Request)(nil), "pb.Request")
	proto.RegisterType((*Response)(nil), "pb.Response")
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor_77a6da22d6a3feb1) }

var fileDescriptor_77a6da22d6a3feb1 = []byte{
	// 471 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x52, 0x5d, 0x8f, 0x93, 0x40,
	0x14, 0xed, 0x0c, 0x65, 0x81, 0xbb, 0x65, 0x9d, 0xbd, 0x6e, 0x36, 0x3c, 0x18, 0x43, 0x36, 0x9a,
	0x90, 0x9a, 0x34, 0xf1, 0x23, 0xd1, 0x67, 0x4d, 0x7c, 0xb2, 0x2f, 0xa3, 0xcf, 0x26, 0x7c, 0x4c,
	0x29, 0x06, 0x18, 0x96, 0xa1, 0x8d, 0xdd, 0x57, 0xff, 0x86, 0x3f, 0xd6, 0xcc, 0xf0, 0x51, 0xea,
	0xdb, 0x3d, 0xe7, 0x9e, 0x03, 0x87, 0x73, 0x01, 0xaf, 0x6d, 0xd2, 0x4d, 0xd3, 0xca, 0x4e, 0x22,
	0x6d, 0x92, 0x87, 0xbf, 0x14, 0xac, 0xad, 0xca, 0x31, 0x00, 0xe7, 0x28, 0x5a, 0x55, 0xc8, 0x3a,
	0x20, 0x21, 0x89, 0x28, 0x1f, 0x21, 0xde, 0x00, 0x2d, 0xb2, 0x80, 0x86, 0x24, 0xb2, 0x38, 0x2d,
	0x32, 0x7c, 0x0d, 0x4e, 0xa5, 0xf2, 0x1f, 0xa7, 0x46, 0x04, 0x56, 0x48, 0xa2, 0x9b, 0x77, 0xd7,
	0x9b, 0x26, 0xd9, 0x6c, 0x7b, 0x8a, 0x8f, 0x3b, 0xbc, 0x03, 0x3b, 0x89, 0xbb, 0x74, 0x1f, 0x2c,
	0x43, 0x12, 0xb9, 0xbc, 0x07, 0xf8, 0x06, 0xbc, 0x54, 0x66, 0x22, 0x35, 0x76, 0xdb, 0xd8, 0x7d,
	0x6d, 0xff, 0x32, 0x92, 0xfc, 0xbc, 0xc7, 0x0f, 0xb0, 0x4a, 0x65, 0xd5, 0xb4, 0x42, 0x29, 0xa3,
	0xbf, 0x32, 0x7a, 0xd6, 0xeb, 0xcf, 0x3c, 0xbf, 0x50, 0xe1, 0x47, 0xf0, 0x47, 0xfc, 0x4d, 0x1c,
	0x45, 0x19, 0x38, 0xc6, 0x76, 0x3b, 0xb7, 0x99, 0x05, 0xbf, 0xd4, 0x21, 0xc2, 0x32, 0x8b, 0xbb,
	0x38, 0x70, 0x43, 0x12, 0xad, 0xb8, 0x99, 0x1f, 0xde, 0x82, 0xfd, 0xd9, 0x04, 0xbf, 0x03, 0x3b,
	0x56, 0xa7, 0x3a, 0x35, 0xed, 0xb8, 0xbc, 0x07, 0x93, 0x85, 0x86, 0xd6, 0x64, 0xf9, 0x43, 0xc0,
	0xe1, 0xe2, 0xf1, 0x20, 0x54, 0x37, 0x74, 0xa7, 0x2d, 0x4b, 0xd3, 0xdd, 0x3d, 0x5c, 0x55, 0xa2,
	0xdb, 0xcb, 0xbe, 0x4f, 0x8f, 0x0f, 0x08, 0x5f, 0x80, 0x57, 0xcb, 0xc1, 0x64, 0x5a, 0x75, 0xf9,
	0x99, 0xc0, 0x97, 0x00, 0x1a, 0xa8, 0x46, 0xd6, 0x4a, 0x0c, 0x7d, 0xce, 0x98, 0x29, 0x85, 0x3d,
	0x0b, 0xfe, 0x15, 0xdc, 0x69, 0xff, 0x7f, 0x8a, 0x73, 0xea, 0x49, 0xaf, 0x93, 0x89, 0xb6, 0xdd,
	0xaa, 0xdc, 0xbc, 0xde, 0xe3, 0x03, 0x5a, 0xbf, 0x02, 0x67, 0x38, 0x2d, 0x3a, 0x60, 0xb5, 0xe2,
	0x91, 0x2d, 0xfa, 0x41, 0x31, 0xa2, 0x87, 0xbd, 0x88, 0x19, 0x5d, 0x6f, 0xc1, 0x9b, 0x2e, 0x88,
	0xd7, 0xe0, 0x14, 0xf5, 0x31, 0x2e, 0x8b, 0x8c, 0x2d, 0xd0, 0x85, 0xe5, 0x2f, 0x25, 0x6b, 0x46,
	0x70, 0x05, 0xae, 0xf9, 0xed, 0x92, 0xc3, 0x8e, 0x51, 0x6d, 0xfd, 0x5d, 0x95, 0xcc, 0xd2, 0x43,
	0x2e, 0x13, 0xb6, 0x44, 0x0f, 0xec, 0xe4, 0xd4, 0x09, 0xc5, 0xec, 0xf5, 0x27, 0x58, 0xcd, 0x0f,
	0xac, 0x57, 0xb5, 0x4c, 0x65, 0xc5, 0x16, 0x7a, 0xdc, 0x95, 0x71, 0x27, 0x18, 0xd1, 0x8f, 0x7e,
	0x2a, 0x8b, 0x84, 0x51, 0x3d, 0xe5, 0x4f, 0x45, 0xc3, 0xac, 0xf5, 0x4f, 0xf0, 0x2f, 0x6e, 0x8c,
	0xb7, 0xe0, 0xd7, 0x72, 0xa4, 0x0a, 0x59, 0xb3, 0x05, 0xfa, 0xe0, 0x25, 0x42, 0x75, 0xdf, 0x1b,
	0x21, 0x32, 0x46, 0xf0, 0x39, 0x3c, 0xd3, 0x70, 0xae, 0xa1, 0x78, 0x0f, 0x98, 0x89, 0x5d, 0x7c,
	0x28, 0x2f, 0x78, 0x2b, 0xb9, 0x32, 0x9f, 0xf0, 0xfe, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x93,
	0xb7, 0xb7, 0x63, 0x46, 0x03, 0x00, 0x00,
}
